/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rb.aoc21.day10.utilities

import com.rb.aoc21.day10.list.LinkedList

class StringUtils {
    companion object {
        fun join(source: LinkedList): String {
            return JoinUtils.join(source)
        }

        fun split(source: String): LinkedList {
            return SplitUtils.split(source)
        }
    }
}
