[package]
name = "aoc_2021_122001"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
env_logger = "0.9.0"
arrayvec = "0.7.2"
quadtree_rs = "0.1.2"
num-traits = "0.2.14"