/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rb.com.aoc21.day05.utilities

import rb.com.aoc21.day05.list.LinkedList

class StringUtils {
    companion object {
        fun join(source: LinkedList): String {
            return JoinUtils.join(source)
        }

        fun split(source: String): LinkedList {
            return SplitUtils.split(source)
        }

        fun lines(source: String): List<String> {
            return source.lines()
        }

        infix fun splitToInt(source: String): List<Int> {
            return lines(source).mapNotNull(String::toInt)
        }

        infix fun splitToInt(source: List<String>): List<Int> {
            return source.mapNotNull(String::toInt)
        }
    }
}
