/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.rb.aoc21.day10.app

import com.rb.aoc21.day10.list.LinkedList

import static com.rb.aoc21.day10.utilities.StringUtils.join
import static com.rb.aoc21.day10.utilities.StringUtils.split
import static com.rb.aoc21.day10.app.MessageUtils.getMessage

import org.apache.commons.text.WordUtils

class App {
    static void main(String[] args) {
        LinkedList tokens
        tokens = split(getMessage())
        String result = join(tokens)
        println(WordUtils.capitalize(result))
    }
}
