/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.rb.aoc21.day10.app

import groovy.transform.PackageScope

@PackageScope
class MessageUtils {
    static String getMessage() {
        return "Hello      World!"
    }
}
