/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rb.com.aoc21.day01.app

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
