/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("rb.com.aoc21.day05.kotlin-application-conventions")
    application

}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("org.slf4j:slf4j-log4j12:1.7.32")
    implementation("org.slf4j:slf4j-api:1.7.32")
    implementation("io.github.microutils:kotlin-logging:2.1.21")
    implementation("com.github.ajalt.clikt:clikt:3.2.0")

    testImplementation(kotlin("test"))
}

application {
    // Define the main class for the application.
    mainClass.set("rb.com.aoc21.day05.app.AppKt")
}

tasks.test {
    useJUnitPlatform()
}