/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("rb.com.aoc21.day01.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
//    implementation("com.jcabi:jcabi-log:0.20.1")
//    implementation("org.slf4j:slf4j-simple:1.7.32")
    implementation("org.slf4j:slf4j-log4j12:1.7.32")
    implementation("org.slf4j:slf4j-api:1.7.32")
    implementation("io.github.microutils:kotlin-logging:2.1.21")
}

kotlin {
    sourceSets {
        all {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-cli:0.3.4")
            }
        }
    }
}

application {
    // Define the main class for the application.
    mainClass.set("rb.com.aoc21.day01.app.AppKt")
}
